### ISSUE TITLE
What's this `instances_test.json` in `run_batch.py`?

### ISSUE THREAD

**Issue by felicitia** [MulongXie/UIED#10]
Hi @MulongXie , I'm trying to run UIED in patch and I'm looking at `run_batch.py`. 
In this line `data = json.load(open('E:/Mulong/Datasets/rico/instances_test.json', 'r'))`
what is this json file and what should I substitute it with? Thank you very much!

**Comment by MulongXie** [comment]
Hi, it's just a data file recording all the paths of your testing GUIs. You can just ignore it and set your testing images in the variable ``input_imgs`` .
