### ISSUE TITLE
What's the unit used in `compo.json` results?

### ISSUE THREAD

**Issue by felicitia** [MulongXie/UIED#11]
Hello @MulongXie, I'm running UIED v2.3 and got the results. It looks like `compo.json` contains a comprehensive result of all detected components. I have a few questions on what the result means in `compo.json`.

1. in `"img": { "shape": [
            800,
            450,
            3
        ] }`
what's the unit used in 800, 450, 3? And what are they?

2. Similarly, for each component, what's the unit used in `column_min`, `row_min`, `height`, `width`, `column_max`, `row_max`? And what are they? (I can guess based on the names but wanted to confirm with you :))

Thank you very much!

**Comment by MulongXie** [comment]
For the sake for processing speed, the non-text detection resizes the GUI to 800-pixel height while keeps its aspect ratio. So the resulting image is 800-pixel height, 450-pixel width and 3-channel (rgb).

(column_min, row_min) is the left-top corner of a compo, (column_max, row_max) is the right-bottom corner of a compo.
