### ISSUE TITLE
merging result issue in an example

### ISSUE THREAD

**Issue by felicitia** [MulongXie/UIED#12]
Hi @MulongXie I have an interesting example (see attached). It seems after merging, some components are merged unnecessarily in the final result (e.g., Account, Favorite, ... all merged to 1 huge component). BTW, the ocr results are fine (also attached FYI). I think it should have something to do with the merging. Do you have any insights on why this happens? I'm running v2.3. Your thoughts are very much appreciated! I'll also look into merge.py... 

![result](https://user-images.githubusercontent.com/5572614/126400142-c9ff4b67-5bd3-4b41-a68d-af3d2445aba5.jpg)

![6pm-video-signin-1-bbox-0189-screen](https://user-images.githubusercontent.com/5572614/126400292-db392c17-1033-46f3-9d85-9a0a9075bd7a.png)

**Comment by MulongXie** [comment]
This is because the parameter ``merge-contained-ele``, change it to False in the run file and try again. 

BTW, I revised the merging rule in a more "smart" way by detecting "block" in the latest version (will be released soon), plz give it a try if you want.

**Comment by felicitia** [comment]
Hi @MulongXie , Chunyang also told me that and I already tried it before. After trying on more examples, the merged results are much better for my purpose and I'd prefer enabling it. For example, the result without merging is attached and the text is not merged with the left icon in the side bar; and on the right, "More" and "Shop" are not shown as a complete button anymore. So I really like the merging feature :) Do you mean the "smart" merging is already implemented and will be released soon? I'm very looking forward to it!

I've also taken a closer look at the code, and added more heuristics in `merge.py` to merge stuff in the cases that I'm interested in. But for this particular example, I haven't figured out how to merge "Account", "Favorite" etc in the same way as "Home"/"Department". Can you point to the relevant part in the code that I can modify? Again, I'm using v2.3 so I'm working with this version of `merge.py`: https://github.com/MulongXie/UIED/blob/814a8e70db69947ad5e3a25bbb411d7db8914cbc/merge.py

![result](https://user-images.githubusercontent.com/5572614/126534807-11a21415-4582-4fba-a3dd-2dae53f3d166.jpg)

**Comment by MulongXie** [comment]
Hi @felicitia, sorry for the late reply, I have been overwhelmed by tons of code and papers lately. 

I just updated the UIED with block recognition algorithm. Now the elements contained in a block will not be removed. 

You can check the algorithm in `detect_compo/lib_ip/ip_detection.py` line 355 function `def is_block()`.

**Comment by felicitia** [comment]
that's great news! thanks for letting me know @MulongXie I'm also a bit overwhelmed lately due to a deadline and I'll check this out soon! BTW, I've been using v2.3 in batch, which works pretty well overall. looking forward to seeing the improvement!
