### ISSUE TITLE
Error in ocr_detection_google function.

### ISSUE THREAD

**Issue by meetgandhi123** [MulongXie/UIED#20]
I have created my own Google Vision API key, while calling the ocr_detection_google function I am getting the following error.

![image](https://user-images.githubusercontent.com/28274170/190919599-3340f7c3-716e-46d9-8d9a-80ddb5ab8a2d.png)

Error:

![image](https://user-images.githubusercontent.com/28274170/190919622-e35e3051-d016-4756-af40-ed0edf48f351.png)

>>> print(response)
>>> <Response [400]>

**Comment by MulongXie** [comment]
Hi, this kind of error is usually caused by some connection failure of Google API. You can print out the `response.json()` out to check the detailed reason.
